### ISSUE TITLE
Changes to Lab

### ISSUE THREAD

**Issue by amjack59** [learn-co-curriculum/bootstrap-image-carousel-code-along#2]
There are some issues that are inherent on many of these labs (including this one) that I thought I would raise. The videos are well made and the narrator very good. However, they were made awhile back and the instructions are misleading often times. For example, the creation of the Carousel in this lab does not work as in the video until the images are added to the Bootstrap code later in the video. Before adding the images, the carousel looks smaller (height wise) that it does in the video leading one to believe that it was done incorrectly when in fact it was not and with the additions of the pictures later all is good. I personally spent about 2 hours trying to figure out what went wrong with my carousel code before moving on to more of the video, so essentially I wasted those hours for nothing which is not good for any of us. I asked for help on the learn site and another student chimed in that he had the same problem the previous night and it also cost him a lot of time before he realized what was going on and related it to me. 

The lab videos do not make reference to Nitrous etc. and so the instructor references creating branches and merges that are not necessary for many people and new students might not understand that you have to read between the lines and use the Learn environment to fork and clone the new repositories for instance. I found myself manually forking and cloning as well as adding, committing and  pushing the repositories and then creating the pull requests via github so that the labs could be completed without Nitrous. This was confusing to me at first and probably will be to others now and in the future.

Lastly, the last two labs I have worked on, had no files created for them as most of the labs do. I get that part of these labs, including this one was to create index and property files and the code along to get practice, and thats great. However, there are assets that still need to be there (image files in this case as well as the js files for the Bootstrap jQuery etc.. This is not mentioned at all in the labs and this can be and surely will be a sticking point with new coders wondering why there code may not work since those files are not there in the labs from the start. 

As time goes on we will all learn enough to get better at improvising and making up for the gaps in the old videos versus the newer course updates but I know it has cost me extra precious hours that were unnecessary. I do not mind the effort mind you, I enjoy solving problems and I think much of this would be explained in a classroom setting, but with us online students it makes it more challenging. Maybe an addendum to the lessons and labs can mention things like this to make sure the students understand exactly what is needed would help a lot. I hope this has been constructive feedback as I really like the program and hope to do very well and hope others do too. Thanks for the consideration.

**Comment by gooryalhamed** [comment]
Hi, you are right when you said that the carousel doesn't look like the video except after adding the images. This is really confusing and wasting our time to find out what's wrong in the code.

**Comment by gj** [comment]
Removed the lesson until we can get a better video up. Thanks @amjack59 !
