### ISSUE TITLE
Mistake in the video and another issues

### ISSUE THREAD

**Issue by gooryalhamed** [learn-co-curriculum/bootstrap-image-carousel-code-along#4]
I think there is a mistake in this video at the end of the lesson, when he typed 
.carousel-caption p{
    display: none;
  }
outside of media query of small-devices and this will cause disappearing of the paragraph in the normal case.
Another issue is the folders we need in this lab and a couple of previous labs are not existing so that I was obliged to import all necessary folders and files on after another each time.

**Comment by gj** [comment]
Removed the lesson until we can get a better video up. Thanks @gooryalhamed !
